import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-version="fix-v5-applied"
      >
        <div style={{ position: 'fixed', bottom: 0, right: 0, background: 'red', color: 'white', fontSize: '10px', zIndex: 9999, padding: '2px 5px' }}>
          V5 FIX APPLIED
        </div>
        {children}
      </body>
    </html>
  );
}
